# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'roam_ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'

  # Pods for roam_ios

  target 'roam_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'roam_iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
